version: '3.8'

name: home-auto

services:
  db:
    image: postgres:16
    ports:
      - 9000:5432      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: home-auto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password   

volumes:
  postgres_data: