# @hostDomain = http://localhost:8080
@hostDomain = http://rpi4.local:8080

GET {{hostDomain}}/ping


### Add New Measurement
POST {{hostDomain}}/measurement
content-type: application/json

{
    "roomId": 1, 
    "timestamp": 1732667724,
    "temperature": 21.1,
    "humidity": 50.0
}

### Get all rooms
GET {{hostDomain}}/api/rooms
content-type: application/json

